# Generated by Django 5.0.6 on 2024-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_delete_advantage_delete_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='articles/images/')),
            ],
        ),
    ]
