# Generated by Django 5.0.6 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/img/default.jpg', upload_to='services/img/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
