# Generated by Django 5.0.6 on 2024-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pagereview_delete_pagecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='PageReview',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
